language: ruby
rvm:
 - 2.3.1
before_install:
# https://github.com/github/git-lfs/issues/880
  - ls -a
  - pwd
  - git clone https://github.com/github/git-lfs.git
  - cd git-lfs
  - git checkout 05666983c2e19664b8fc47c30b767ec160e3fea5
  - script/bootstrap
  - cd ..
  - ls -a
  - pwd
  - git-lfs/bin/git-lfs init | cat
  - git-lfs/bin/git-lfs env  | cat
  - git-lfs/bin/git-lfs pull | cat
install:
  - bundle
script: rake compile && rake spec:all
